name: mid_term
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_ui_auth: ^1.16.1
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.5
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  cupertino_icons: ^1.0.5

flutter:
  uses-material-design: true