// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBtf-FFkrIj3Ymo3G-tTqSpBSEPgX7qQw',
    appId: '1:537765072874:web:aedf33f6608ce96e5bec93',
    messagingSenderId: '537765072874',
    projectId: 'remoteconfig-c8b11',
    authDomain: 'remoteconfig-c8b11.firebaseapp.com',
    storageBucket: 'remoteconfig-c8b11.firebasestorage.app',
    measurementId: 'G-EYZ184KQGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFxhbWLjSKKChAjZrbeKXX6bh792vvd2A',
    appId: '1:537765072874:android:11a9445962065dee5bec93',
    messagingSenderId: '537765072874',
    projectId: 'remoteconfig-c8b11',
    storageBucket: 'remoteconfig-c8b11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyw0P5kIhLqt8eAwu4dbOTfCSqIIKZ-Rg',
    appId: '1:537765072874:ios:c6620172ae7a09b45bec93',
    messagingSenderId: '537765072874',
    projectId: 'remoteconfig-c8b11',
    storageBucket: 'remoteconfig-c8b11.firebasestorage.app',
    iosBundleId: 'com.example.midTerm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyw0P5kIhLqt8eAwu4dbOTfCSqIIKZ-Rg',
    appId: '1:537765072874:ios:c6620172ae7a09b45bec93',
    messagingSenderId: '537765072874',
    projectId: 'remoteconfig-c8b11',
    storageBucket: 'remoteconfig-c8b11.firebasestorage.app',
    iosBundleId: 'com.example.midTerm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBtf-FFkrIj3Ymo3G-tTqSpBSEPgX7qQw',
    appId: '1:537765072874:web:56812eaf449c953f5bec93',
    messagingSenderId: '537765072874',
    projectId: 'remoteconfig-c8b11',
    authDomain: 'remoteconfig-c8b11.firebaseapp.com',
    storageBucket: 'remoteconfig-c8b11.firebasestorage.app',
    measurementId: 'G-H3DSVECC15',
  );
}
